server:
  port: 9670
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yuxiang_edu_trade?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Ren666665
  redis:
    host: localhost
    port: 6379
    database: 0
    lettuce: # 密码
      pool:
        max-active: 10
        max-wait: -1
        max-idle: 2 #最大空闲连接数
        min-idle: 0 #最小空闲连接数

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/yuxiang/edu/service/trade/mapper/xml/*.xml

# 负载均衡策略
#service-oss:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

ribbon:
  MaxAutoRetries: 1 # 同一实例最大重试次数，不包括首次调用，默认为0
  MaxAutoRetriesNextServer: 1 # 重试其他实例的最大重试次数，不包括首次所选的server，默认为1
  ConnectTimeout: 10000 # 连接建立的超时时长，默认1秒
  ReadTimeout: 10000 # 处理请求的超时时间，默认1秒