server:
  port: 9600
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务进行路由
      routes:
        - id: service-acl
          uri: lb://service-acl
          predicates:
            - Path=/*/acl/**
        - id: service-core
          uri: lb://service-core
          predicates:
            - Path=/*/core/**
        - id: service-ams
          uri: lb://service-ams
          predicates:
            - Path=/*/ams/**
        - id: service-mms
          uri: lb://service-mms
          predicates:
            - Path=/*/mms/**
        - id: service-oss
          uri: lb://service-oss
          predicates:
            - Path=/*/oss/**
        - id: service-sms
          uri: lb://service-sms
          predicates:
            - Path=/*/sms/**
        - id: service-statistics
          uri: lb://service-statistics
          predicates:
            - Path=/*/statistics/**
        - id: service-trade
          uri: lb://service-trade
          predicates:
            - Path=/*/trade/**
        - id: service-ucenter
          uri: lb://service-ucenter
          predicates:
            - Path=/*/ucenter/**
        - id: service-vod
          uri: lb://service-vod
          predicates:
            - Path=/*/vod/**
#  zipkin:
#    base-url: http://localhost:9411
#    sender:
#      type: web # 数据传输方式，
#    sleuth:
#      sampler:
#        probability: 1 # 收集数据百分比


#  redis:
#    host: localhost
#    port: 6379
#    database: 0
#    lettuce: # 密码
#      pool:
#        max-active: 10
#        max-wait: -1
#        max-idle: 2 #最大空闲连接数
#        min-idle: 0 #最小空闲连接数