server:
  port: 9640
spring:
  servlet:
    multipart:
      max-file-size: 4MB # 单个文件大小
      max-request-size: 20MB # 单次上传大小
#  zipkin:
#    base-url: http://localhost:9411
#    sender:
#      type: web # 数据传输方式，
#  sleuth:
#    sampler:
#      probability: 1 # 收集数据百分比