server:
  port: 9630

netty:
  port: 8888


ribbon:
  MaxAutoRetries: 1 # 同一实例最大重试次数，不包括首次调用，默认为0
  MaxAutoRetriesNextServer: 1 # 重试其他实例的最大重试次数，不包括首次所选的server，默认为1
  ConnectTimeout: 10000 # 连接建立的超时时长，默认1秒
  ReadTimeout: 10000 # 处理请求的超时时间，默认1秒